{{- if .Values.app.connectsToDB }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.inventoryDb.name }}
  name: {{ .Values.inventoryDb.name }}
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ .Values.inventoryDb.name }}
{{- end }}