apiVersion: v2
name: coolstore-microservice-common
description: A Common chart for the coolstore microservice in the MAD workshop
icon: https://static.redhat.com/libs/redhat/brand-assets/latest/corp/logo.svg
type: application
version: 1.0.0
appVersion: "1.0.0"